[project]
name = "chatbot-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "langchain>=1.0.3",
    "langchain-community>=0.4.1",
]
